version: "3.9"


services:
  web:
    tty: true
    build: .
    command: sh -c " 
      python manage.py makemigrations 
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/notification_service
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - celery
    networks:
      - default
      - service-proxy

  celery:
    build: .
    command: >
      sh -c "python -m celery -A config worker -l info"
    volumes:
      - .:/notification_service
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - default
      - service-proxy

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - default
      - service-proxy

  redis:
    image: redis
    restart: always
    command: redis-server
    env_file:
      - .env
    ports:
      - 6377:6379
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - default
      - service-proxy

volumes:
  postgres_data:
  redis_data:

networks:
  service-proxy: